[project]
name = "ordyswap"
description = "Demonstrates trustless atomic swaps between Ordinals and Stacks"
authors = []
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SP1WN90HKT0E1FWCJT9JFPMC8YP7XGBGFNZGHRVZX.clarity-bitcoin"

[contracts.ord-swap]
path = "contracts/ord-swap.clar"
clarity_version = 1
epoch = 2.05

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
